import { useEffect, useState } from 'react';
import { adminService } from '../../services';
import { useToast } from '../../context/ToastContext';
import Spinner from '../../components/Spinner';
import { getApiError } from '../../utils/helpers';

const empty = { name:'',email:'',contactNumber:'',password:'',classIds:[] };
export default function AdminUsers(){
  const {toast}=useToast();const [data,setData]=useState(null);const [form,setForm]=useState(empty);const [deptForm,setDeptForm]=useState({name:'',email:'',password:'',departmentId:''});const [busy,setBusy]=useState(false);
  const load=()=>adminService.getUsers().then(r=>setData(r.data)).catch(e=>toast(getApiError(e),'error'));
  useEffect(()=>{load();},[]);
  if(!data)return <Spinner label="Loading user management..."/>;
  const set=(key,value)=>setForm(v=>({...v,[key]:value}));
  const create=async e=>{e.preventDefault();setBusy(true);try{await adminService.createCoordinator(form);toast('Coordinator created.','success');setForm(empty);load();}catch(e){toast(getApiError(e),'error');}finally{setBusy(false);}};
  const change=async user=>{const role=user.role==='ADMIN'?'COORDINATOR':'ADMIN';if(!window.confirm(`Are you sure you want to change ${user.name} from ${user.role} to ${role}?`))return;try{await adminService.changeRole(user.id,role);toast('Role updated.','success');load();}catch(e){toast(getApiError(e),'error');}};
  const createDepartment=async e=>{e.preventDefault();setBusy(true);try{await adminService.createDepartmentUser(deptForm);toast('Department account created.','success');setDeptForm({name:'',email:'',password:'',departmentId:''});load();}catch(e){toast(getApiError(e),'error');}finally{setBusy(false);}};
  return <div className="space-y-6"><div><h2 className="text-lg font-bold text-slate-800">User Management</h2><p className="text-sm text-slate-500">Create coordinators and department accounts, and manage privileged access.</p></div>
  <section className="card overflow-hidden"><h3 className="border-b p-5 font-semibold">Coordinators and administrators</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Name</th><th className="p-4">Email</th><th className="p-4">Role</th><th className="p-4">Classes</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y">{data.users.filter(u=>u.role!=='DEPARTMENT').map(u=><tr key={u.id}><td className="p-4 font-medium">{u.name}</td><td className="p-4">{u.email}</td><td className="p-4">{u.role}</td><td className="p-4">{u.managedClasses.map(c=>c.className).join(', ')||'—'}</td><td className="p-4">{u.id!==JSON.parse(localStorage.getItem('campus_user')||'{}').id&&<button className="text-brand-600 hover:underline" onClick={()=>change(u)}>{u.role==='ADMIN'?'Make Coordinator':'Make Admin'}</button>}</td></tr>)}</tbody></table></div></section>
  <div className="grid gap-6 lg:grid-cols-2"><form className="card space-y-4 p-5" onSubmit={create}><h3 className="font-semibold">Create Coordinator</h3><input className="input" placeholder="Full name" required value={form.name} onChange={e=>set('name',e.target.value)}/><input className="input" type="email" placeholder="Email" required value={form.email} onChange={e=>set('email',e.target.value)}/><input className="input" placeholder="Contact number" value={form.contactNumber} onChange={e=>set('contactNumber',e.target.value)}/><input className="input" type="password" placeholder="Temporary password (8+ characters)" minLength="8" required value={form.password} onChange={e=>set('password',e.target.value)}/><label className="block text-sm font-medium">Assigned classes<select multiple className="input mt-1 min-h-32" required value={form.classIds} onChange={e=>set('classIds',Array.from(e.target.selectedOptions,o=>o.value))}>{data.classes.map(c=><option key={c.id} value={c.id}>{c.className}</option>)}</select><span className="text-xs text-slate-500">Use Ctrl/Cmd to select multiple classes.</span></label><button className="btn-primary" disabled={busy}>{busy?'Creating...':'Create Coordinator'}</button></form>
  <form className="card space-y-4 p-5" onSubmit={createDepartment}><h3 className="font-semibold">Create Department Account</h3><input className="input" placeholder="Full name" required value={deptForm.name} onChange={e=>setDeptForm(v=>({...v,name:e.target.value}))}/><input className="input" type="email" placeholder="Email" required value={deptForm.email} onChange={e=>setDeptForm(v=>({...v,email:e.target.value}))}/><input className="input" type="password" minLength="8" placeholder="Temporary password (8+ characters)" required value={deptForm.password} onChange={e=>setDeptForm(v=>({...v,password:e.target.value}))}/><select className="input" required value={deptForm.departmentId} onChange={e=>setDeptForm(v=>({...v,departmentId:e.target.value}))}><option value="">Select department</option>{data.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="btn-primary" disabled={busy}>{busy?'Creating...':'Create Department Account'}</button></form></div>
  <section className="card overflow-hidden"><h3 className="border-b p-5 font-semibold">Department accounts</h3><div className="divide-y">{data.users.filter(u=>u.role==='DEPARTMENT').map(u=><div className="flex justify-between p-4 text-sm" key={u.id}><span>{u.name} · {u.email}</span><span>{u.department?.name||'Unassigned'}</span></div>)}</div></section></div>;
}
